name: Optimize
on:
  # Comment the next line if you don't want the Action to run on Pull Requests.
  pull_request:
    branches:
      - main
jobs:
  svgs:
    name: SVGs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Uncomment the next 2 lines to select a branch for schedule or dispatch.
      #   with:
      #     ref: main
      - uses: ericcornelissen/svgo-action@v3
        with:
          svgo-version: 3
          repo-token: ${{ secrets.GITHUB_TOKEN }}
